services:
  mongo:
    image: mongo:8.0
    container_name: restcontrol-TC2-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: restcontrol_TC2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restcontrol-TC2-app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/restcontrol-tc2

volumes:
  mongo_data:
